### ISSUE TITLE
It's possible to only partially highlight a word in the annotation editor

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#448]
I'm having a difficult time replicating this, but I was able to highlight two words in the annotation editor but not highlight the first letter in the word.

Resulting in a "United States" with two U's:
https://www.dropbox.com/s/xkns3g291d3zqks/Screenshot%202015-01-08%2011.11.08.png

Here's the video and annotation I was working on:
http://sartre3.byu.edu:9006/annotations/211/

Most of the time the annotation doesn't work with highlighting more than one word, and I can't seem to recreate this bug, but I did get it to happen once, so possibly look over and see if there's anything that might have caused that. There might be an off by one error for the beginning of lines.

**Comment by gliese1337** [comment]
This has nothing to do with highlighting two words; it's an error with annotating words that occur at the beginning of text nodes: the very beginning of the text, and immediately after an HTML tag. It is due to an off-by-one error in the matching system that fails to distinguish between a match exactly at the beginning and a match starting one character in.
