### ISSUE TITLE
Annotation- Audio, if the user doesn't click "pause" the audio will continue playing with no way to stop it.

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#453]
Try clicking on "the," and then play the song.
http://sartre3.byu.edu:9006/content/208

Then click on another annotation or perhaps continue playing the video. The Audio will not stop playing, and if the user goes back to the word to stop it, the annotation will only create another instance of the audio.

**Comment by gliese1337** [comment]
Not stopping when you play the video is expected behavior. At that point, the annotation is still active, just hidden, and you can go back to the annotations tab and stop it. We may want to pause any media annotations when the tab is hidden, but that should be a separate issue.

It is, however, genuinely problematic that the sound keeps playing when the annotation is destroyed by the activation of a new annotation. We ought to avoid destroying and rebuilding a new instance when the same annotation is activated twice in a row, and video/sound should be properly cleaned up when annotations are actually destroyed.

**Comment by gliese1337** [comment]
Like many other issues, this will become far easier to handle once #297 is solved.
