### ISSUE TITLE
Firefox-Mac- Was able to highlight a word, doesn't stay highlighted in video player

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#454]
The word is "Panama," and I can see it saved as an annotation for the annotations named "Firefox Annotations," but the video player leaves it as normal.
https://www.dropbox.com/s/hreporl48wvpju0/Screenshot%202015-01-10%2012.29.59.png

I haven't been able to replicate the bug.
http://sartre3.byu.edu:9006/annotations/208/

**Comment by gliese1337** [comment]
"Panama" and "Haiti" are separated by a line break in the actual subtitle file. In the transcript viewer used in the Annotation Editor, this is turned into a space. When rendered as a subtitle, however, the line break character is replaced by an HTML BR element.
Prior to applying annotation styles, the annotator filters out annotations for words that do not occur in the current text, so that there will be less Stuff to consider in each iteration of the annotation loop. It does this by looking at the raw textContent of the HTML node currently being annotated. Since the line break was previously replaced by a BR element, the removal of the BR element results in "PanamaHaiti" looking like a single word, and thus the annotations for both "Panama" and "Haiti" are filtered out.
The ideal fix is to change the way the filtering is done so it doesn't incorrectly discard that space, without negatively impacting annotator efficiency too much.
