### ISSUE TITLE
YouTube Video Scrub Bar Snaps to Place only when playing.

### ISSUE THREAD

**Issue by verdude** [BYU-ARCLITE/Ayamel-Examples#482]
If a YouTube video is paused and then the user changes the position of the current time marker, it won't change the position of the progress marker until the video resumes playing.

**Comment by gliese1337** [comment]
This is similar to #279 , but not exactly the same. I did a really terrible job of documenting the fix for that one, although I'm fairly sure it's related to https://github.com/BYU-ARCLITE/Ayamel.js/commit/62ca8b296160b1e4e1b8d1f7f7a3de5fffdc93e1

The problem this time is probably something to do with the YouTube IFrame player not producing timeupdate events when it isn't playing, and asynchrony meaning that the updated time isn't available until you return to the event loop (like what happened with the mute button).

**Comment by gliese1337** [comment]
On further investigation, this looks like exactly the same problem as #279 after all. Still probably something to do with the communication between the YouTube IFrame player and the Ayamel Player.
