### ISSUE TITLE
Incapability of streaming option from brightcove and Ayamel player 

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#489]
I was trying to compare the differences between streaming from Brightcove and using progressive download on the Monsieur Batignole film that we have on the Beta sight: http://sartre3.byu.edu:9006/content/428.  When I set the media source with a link with the streaming option, the player no longer worked. Its not that it didn't play, but it didn't show up at all. Whereas the link for the progressive download worked just fine: http://sartre3.byu.edu:9006/content/427.

https://www.dropbox.com/s/865xwwlmzm1p03e/Screenshot%202015-02-20%2011.28.00.png?dl=0

**Comment by gliese1337** [comment]
Those appear to both be pointing at the same resource, with a downloadURI of http://c.brightcove.com/services/mobile/streaming/index/rendition.m3u8?assetId=1614505040001
Neither of them render a video player.
That is neither a link to a video file (which would be played with the HTML5 player) nor a Brightcove Experience URL (which would be played by the Brightcove player). It's a link to a text-based playlist file, which contains a list of URLs to video files containing small segments of the original video. It is thus unsurprising that none of our existing plugins know what to do with it, and thus no video is rendered (because as far as our software is concerned, that's not a video file- it's text!)

Windows media player and VLC can play the segments, and VLC can interpret the playlist file. I have not been able to get an HTML5 player to play the segments, but it might be possible. Thus, it is conceivable that we could write a new plugin that would interpret the playlist file and properly play back the individual segments.

That, however, would be a ridiculous amount of work to replicate something that Brightcove in all likelihood has already done. So: where did that link come from, and does Brightcove provide any instructions on how it was supposed to have been used?

**Comment by gliese1337** [comment]
Resolved with the addition of the THEOPlayer HLS video player.
