### ISSUE TITLE
Slow Down Button Not Working 

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#512]
Hey guys,
The speed up slow down button isn't working with this video:
http://ayamel.byu.edu/course/349/content/2127
This is the error I get:
https://www.dropbox.com/s/fgyxgh33shebzlw/Screenshot%202015-05-28%2015.47.03.png?dl=0

I have only run into this problem on this specific video.
Thanks!

**Comment by gliese1337** [comment]
Well, that's weird. It should just silently *not work*, not give you an annoying error box when it doesn't work.

The basic issue is that the new Brightcove player *sometimes* supports changing playback speed, and sometimes doesn't (depending on the video, and what you're using, and so on), and I have not yet found a way to detect whether or not it's going to work in any specific case. I left the control activated for Brightcove videos so that it would be available in cases where it does work, but if it's going to sometimes throw up annoying error boxes like that, I guess we'll just have to turn it off entirely.
