### ISSUE TITLE
Move the save button in configuration

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#551]
It would be really nice if the save button were next to the close button. That way people wouldn't miss it because you have to scroll down to see it. Also, it would just be nicer so you don't have to scroll down to save. 
![save](https://cloud.githubusercontent.com/assets/10120523/8196596/968ea7de-144a-11e5-98c0-74415daf53f1.gif)

**Comment by gliese1337** [comment]
Related to #324. We shouldn't bother fixing one without the other.

**Comment by dro248** [comment]
I was working on this a few minutes ago, but I cannot seem to find code for this button anywhere. Strange!

Does anyone know?

**Comment by gliese1337** [comment]
https://github.com/BYU-ARCLITE/Ayamel-Examples/blob/92f583651563b32316348ad66fb632f64419a514/public/javascripts/ContentSettings.js#L70

It's pretty heavily tied up with the code that builds the rest of the configuration controls, and not at all easy to move. Which is why I suggested that this should be done as part of #324, which involves a total redesign of the configuration controls anyway.

**Comment by gliese1337** [comment]
Might as well just consider this subsumed under #324
