### ISSUE TITLE
How do we access public content?

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#553]
I couldn't figure out a way to access public content when not logged in as an administrator. It seems we need a way to do this because it would be helpful for those who are looking for content for their language course. I think the best way to do this would be for their either to be a directory/ tab for public content or a way to search for key words in the search bar such as search a specific language or simply search public content.

**Comment by gliese1337** [comment]
We used to have a tab for public content, and it had to be removed because people *used* it too much, and it crashed the server. If people were much more conservative in how much public content they created, that would not be a problem, but they aren't, and it is.

Public content will be available via site search, once that functionality is re-activated. That is *not*, however, the intended method for finding content for a new language course. Searching public content is intended as a convenience for students and for new users who are just checking out the site for the first time and need something to play around with to get a feel for it. Looking for stuff to use in a new language course should be done by searching the Resource Library.
