### ISSUE TITLE
Have Notifications from Ayamel be sent to User's Email

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#560]
There are professors who would like to have the notifications from Ayamel sent to their email. Some have expressed the fact that they are not often monitoring their Ayamel account because they just have their students use it. Because of that, they would prefer the notifications be sent to their email.

**Comment by shyatt** [comment]
I would also do the same thing with announcements.

**Comment by gliese1337** [comment]
Turns out this is already implemented. If users have listed their e-mail address with their account, they should be getting e-mail notifications. If we have reports that this is not happening, and the users involved have checked that their accounts do, in fact, have e-mails associated with them, then set up a test account using the lab Gmail address so that we can try to replicate the problem, and then re-open this issue.

**Comment by shyatt** [comment]
I tested this feature with the arclitelab@gmail.com email, and I did not
receive an email about a notification.  After waiting ten minutes, I looked
in the spam, inbox, and trash tabs.

Ayamel User:
Arclite Tester
Password:
N3phi&S4m


On Thu, Jun 25, 2015 at 4:36 PM, Logan Kearsley <notifications@github.com>
wrote:

> Closed #560 <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/560>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/560#event-340580263>
> .
>



-- 
Shari Hyatt

**Comment by schyatt** [comment]
In all honesty, it would be nice if users received email notification for the following (if there is an email associated with their account):
1. When someone requests to join their course
2. When there is an announcement in a course they belong to
3. Anytime they get a notification on Ayamel

**Comment by JKJensen** [comment]
Because some people might not want this feature, let's have this "email notifications" option as a box users can uncheck in their user profile.
When a user gets an account on Ayamel they are automatically opted-in to receive email of notifications on Ayamel.

**Comment by verdude** [comment]
@gliese1337, Gmail has a security features which blocks "less secure apps" from using the service. The easiest way to get email up and running would be to set Allow less secure apps to "On". 

![image](https://cloud.githubusercontent.com/assets/5685655/15871316/24a7b130-2cb1-11e6-9ef1-f5ccba81e7b8.png)

This [article](http://www.ghacks.net/2014/07/21/gmail-starts-block-less-secure-apps-enable-access/) mentions that we can set up two factor authentication on the email through which we are sending mail. We would then create an app specific password for Ayamel. Although, since the lab email is a shared account, that might not be the best idea.
