### ISSUE TITLE
Videos from brightcove on Ayamel with the brightcove://videoID as media source won't play

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#561]
Videos from brightcove on Ayamel with the brightcove://videoID as media source won't play
Video url:  https://ayamel.byu.edu/course/349/content/2128

![brightcove](https://cloud.githubusercontent.com/assets/10120523/8315370/7e7e0fc8-19ad-11e5-8c8b-b665209b6043.gif)

**Comment by gliese1337** [comment]
This is a problem on Brightcove's end. Their code tries to do manual protocol-relative URL resolution, and does it wrongly. We've sent them an e-mail detailing exactly where the error occurs, so we just have to wait for them now.

**Comment by gliese1337** [comment]
A temporary fix has been implemented while we wait on Brightcove engineering.

**Comment by gliese1337** [comment]
@dro248 We've got an assignment to re-write the Brightcove player again to use "delayed instantiation" (http://docs.brightcove.com/en/video-cloud/brightcove-player/guides/embed-in-page.html#delayinstantiation), the latest suggestion from Brightcove tech support for how to properly handle dynamic embedding.

Since you assigned yourself this issue, you've got the project. Check the YouTube plugin for how to load the Brightcove player scripts. This should eliminate the need for an IFrame. As before, step 1 is just to get a video on the screen, verifying that the delayed instantiation approach actually works (or discovering that it doesn't, and aborting the project). After that, re-do the interface implementation to interact with the Brightcove player directly instead of using postMessage calls to the IFrame-that-will-no-longer-exist.

**Comment by gliese1337** [comment]
Since Brightcove videos do in fact play right now, I'm moving this issue over the Ayamel.js repository as a possible enhancement: https://github.com/BYU-ARCLITE/Ayamel.js/issues/16
