### ISSUE TITLE
It would be nice if course list showed up alphabetically

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#567]
It would be nice if course list showed up alphabetically
![course](https://cloud.githubusercontent.com/assets/10120523/8361656/6825bdd6-1b31-11e5-80db-f2b559b512e1.gif)

**Comment by gliese1337** [comment]
I think this is fixed. It might be using reverse alphabetical order instead of regular alphabetical order. I don't know who on the beta site is a member of oodles of courses to be able to test it for sure. If it's not actually working right, feel free to re-open this issue after the next release cycle when it can be tested on the main site.

**Comment by shyatt** [comment]
Looks good on the beta site!

On Thu, Jun 25, 2015 at 4:02 PM, Logan Kearsley <notifications@github.com>
wrote:

> I think this is fixed. It might be using reverse alphabetical order
> instead of regular alphabetical order. I don't know who on the beta site is
> a member of oodles of courses to be able to test it for sure. If it's not
> actually working right, feel free to re-open this issue after the next
> release cycle when it can be tested on the main site.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/567#issuecomment-115413405>
> .
>



-- 
Shari Hyatt
