### ISSUE TITLE
Allow Transcript and Definition pane to cover the full length of the video.

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#597]
Right now only 60% of our available space to put Transcript and Definition content is being used.
![image](https://cloud.githubusercontent.com/assets/5481718/8914686/e6cc76b2-345d-11e5-8aa2-8ab4720fd122.png)

The transcript should run the length of that entire window, stopping at the video play bar.

**Comment by gliese1337** [comment]
This turns out to be surprisingly difficult. Sizing of the transcript player relies on a method that only worked due to the specific structure of the old page. CSS doesn't seem to provide the tools necessary to handle sizing properly in this instance.

This may be the best time to finally replace our ad-hoc transcript viewer with another Ayamel MediaPlayer, which would simultaneously take care of #179 .

**Comment by johnlarson** [comment]
Fixed it on my local machine. It's currently not displaying right on the beta site, but I think that's just because I only pulled the changes into Ayamel-Beta, and not into Ayamel.js. How do I get the changes to show up that I made to Ayamel.js?

**Comment by gliese1337** [comment]
@johnlarson copy the new files into /shares/htdocs/libs/Ayamel.js on sartre. That's where we keep the copies of JS libraries that are referenced by the main site.

**Comment by johnlarson** [comment]
Fixed.
