### ISSUE TITLE
Play/Pause functionality when Transcript pane is open

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#598]
If a user presses the play button while the transcript tab is open, then the video should play and the transcript tab should stay open.

However, if a user has a "definitions" tab or an "annotations" tab open, and they press play, then the definitions/annotations pane should close and the video returns to normal.

**Comment by gliese1337** [comment]
Is there any particular justification for closing the definition & annotation tabs automatically?

Leaving it as-is just means that everything still works the same as it did with the old player- the sidebars are just always there- and there is no regression to worry about. And I can easily imagine situations where automatically closing tabs would be very annoying from my point of view as a student.

I won't "wontfix" this yet, but I don't think we should spend time on adding this functionality without a solid UX justification for it.

**Comment by JKJensen** [comment]
From my perspective, Annotations and Definitions are actions that require users to look at the content, and then go back to the video. There isn't much interaction there that needs to occur while a user is watching a video.

But for a transcript, it's better to leave it there as someone watching the transcript would be following along with the video while reading the transcript.


However, if users wanted to leave the pane open, we could have small buttons available in which to leave them open.
![possiblevideoplayertabs](https://cloud.githubusercontent.com/assets/5481718/8921514/ba75463a-3493-11e5-870c-89de97046127.png)

This is something we can probably discuss further next Scrum meeting.

**Comment by gliese1337** [comment]
We *could* have buttons to allow users to toggle auto-hiding on and off. If we do that, however, it would make the most sense to enable the same user-control functionality for all tabs, rather than singling out transcripts as a special tab. While it's true that users interact with transcripts differently from the other two tab types, it's better to keep the interface uniform and minimize one-off idiosyncratic differences.

Adding those extra controls does, however, further complicate an already extremely rich interface, and would produce extra overhead in user training and conscious engagement. Given that they can already manually close tabs when needed, it is my opinion that the advantage of adding controls to turn auto-hiding on and off is not worth the expense in both developer time and added interface complexity. But, I'll wait for a final decision until after the meeting.

**Comment by JKJensen** [comment]
Okay, new plan:

If a user opens a tab, then it should stay open.
If the program opened the tab, then it should close automatically.

For now, don't implement any symbol differentiation for the user between these states.
