### ISSUE TITLE
The controls for the video player disappear when in full screen mode and do not display on hover.

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#611]
On Chrome a user can go to full screen mode and watch content and the controls and video scrub bar disappear. However, if a user moves their mouse to the bottom of the screen the controls will appear again. This is the ideal functionality.

However in Firefox the full screen mode the controls disappear and stay disappeared until out of fullscreen mode.
![screen shot 2015-08-12 at 4 02 09 pm](https://cloud.githubusercontent.com/assets/5481718/9237920/85c81532-410b-11e5-9377-b9b983d9b69a.png)

Firefox should behave the same way as Chrome and enable the controls to appear with a mouse hover.

**Comment by dro248** [comment]
The problem that we are running into is that Firefox is rendering the video toolbar below the scope of the screen. I think this issue is brought about by the differences in interpreting HTML/CSS than Chrome.

**Comment by dro248** [comment]
After speaking with Logan, what I have done is modified the CSS (ayamel.js/css/player.css) in order to standardize the look/feel of the fullscreen mode across different browsers.

**Comment by dro248** [comment]
I adjusted the CSS (ayamel.js/css/player.css) in order to disable ALL video players from being able to screw up the ayamel player layout through pointer events. This means that Youtube (as well as all other players), will be unable to enable their inherent fullscreen mode.

However,The consequences of this patch is a (very, very) slight decrease in functionality as one can no longer click on the video vendor's logo to follow the link to their site.

**Comment by JKJensen** [comment]
Ok, one big problem with this is that users will not be able to press "x" off of youtube banner ads.

**Comment by gliese1337** [comment]
That is a good point. Further tracking of this issue should, however, occur on https://github.com/BYU-ARCLITE/Ayamel.js/issues/18
Since the Ayamel Player can be updated independently from the rest of the site, this need not hold up our release cycle.
