### ISSUE TITLE
Bug logging in via google account on beta site

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#613]
I logged in using my google account, it told me I put in an invalid username/ password (which I didn't), so I clicked on log in using google account again, and then it logged me in (this is really quick on the .gif, but it did log me in). 
![bug](https://cloud.githubusercontent.com/assets/10120523/9257668/0f65c7b4-41b4-11e5-945f-b82fe3ea4bb9.gif)

**Comment by JKJensen** [comment]
If a user is already logged into a Google account and they click "Sign in with Google" they don't run into that problem. However if they aren't logged in yet and they try to run sign in with Google it will give a "You waited too long?" error.


Another thing to note is that some of the functionality of the topbar changes for brand new Google logins.
![screen shot 2015-08-13 at 1 14 52 pm](https://cloud.githubusercontent.com/assets/5481718/9259286/67dd9d0a-41bd-11e5-9ea8-caf8378449e0.png)

When I logged in with previously made ayamel accounts via Google login I had full access, but for new google logins there's no ability to edit user accounts or anything.

Is that by design?

**Comment by gliese1337** [comment]
That is not by design.

**Comment by daganrh** [comment]
There seems to be a timer, such that after a certain number of seconds, such as 10, it will always call that when logging in. So could we just find that timer and make it longer, such as 2 minutes, or 10?

**Comment by gliese1337** [comment]
Maybe. But if that's the cause of the failure, it implies that it must be taking longer than is currently on the timer to complete the Google login process. So, check that, and if that seems to be a reasonable assumption, then go ahead and increase the timer to whatever seems like a reasonable length of time for someone to take to log in.

**Comment by JKJensen** [comment]
On the main site, when a user logs in with a brand new Google account they have basic user permissions.
![screenshot 2015-08-26 14 18 26](https://cloud.githubusercontent.com/assets/5481718/9505077/6d9d1f5a-4bfd-11e5-9074-47f26406bf0f.png)

If we rollover the Beta site as-is, Google logins may lose that functionality and be left like this:
![Screenshot](https://cloud.githubusercontent.com/assets/5481718/9259286/67dd9d0a-41bd-11e5-9ea8-caf8378449e0.png)

However, the problem with not logging in fast enough is a problem on both the main site and the beta site.

**Comment by gliese1337** [comment]
New Google Accounts on the Beta Site seem to be working fine now. I made a trivial change to how user roles are assigned; I don't think that should have had any effect beyond making account creation go a couple microseconds faster, but maybe it did.

**Comment by daganrh** [comment]
the timer was increased, in 
\Ayamel-Examples/app/controllers/authentication/Google.scala
line 77

there is a timer set to 100000, which is 10 seconds, 1 minute 40 seconds, 
if more time is wanted, increase that value and recompile it on the develop branch
