### ISSUE TITLE
 Video player doesn't fit on screen when not in full screen mode

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#624]
The video doesn't fit on the screen when you are in the normal viewing mode (not full screen). You have to scroll down to see the bottom and the controls, and then you can't see the top of the video.
![doesn t fit](https://cloud.githubusercontent.com/assets/10120523/9264375/04f0d4b6-41e3-11e5-8c15-a5eb7f42984d.gif)

**Comment by gliese1337** [comment]
This is fixed by selecting a more appropriate video aspect ratio for the target audience.

**Comment by schyatt** [comment]
I just tested this, and the only aspect ratio that makes the video player fit on the screen is "Widescreen" (which happens to be at the bottom of the list, so who knows if someone would go through all of them before giving up). Maybe we should make that the default.

**Comment by schyatt** [comment]
Of course, the "widescreen" setting doesn't look great in full screen. So what are our options?
 
![full](https://cloud.githubusercontent.com/assets/10120523/9526801/b36de220-4ca8-11e5-9fd2-905da764aac4.gif)

**Comment by gliese1337** [comment]
Any other aspect ratio will look even worse in fullscreen. The video is the size that it is: if it happens not to have the same aspect ratio as your monitor, it *will* get letterboxed. The only thing you can do about that is upload a different version of the video that's been edited to have a different aspect ratio (which will necessarily crop the image).

When not in fullscreen mode, you can make the video shorter by resizing the window to the thinner; the video will resize to match the size of the window, and that means shortening and well as thinning in order to maintain whatever the prescribed aspect ratio is.

It might be possible to add a constraint to the resizing algorithm that will constrain the height to not be more than the viewport height at any time. I'm not sure how that might mess up the rest of the page layout, though. I'll play around with it and see if I can up with anything that doesn't end up looking worse than what we currently have.

**Comment by DigitalProf** [comment]
I find the array of aspect ratios a bit bewildering. I sort of guess I am not the only one. A Google search ("player aspect ratio" lichtenberg) came up with only ONE hit, which had nothing to do with the topic at hand. Your thoughts?

![image](https://cloud.githubusercontent.com/assets/7268293/9610726/88e1d5cc-5098-11e5-8242-130080b2ba31.png)

**Comment by gliese1337** [comment]
If I search for "lichtenberg aspect ratio", the entire first page of results is directly relevant (at the very least telling you what the ratio is and what it looks like), and the first one is the best.

The UI for selecting aspect ratios is pretty bad, but it was the simplest, fastest thing we could implement aside from a free-form text box for people to type in whatever numbers they wanted, which would arguably be even worse. Since the whole configuration dialog was supposed to be redesigned soon, per #551, it didn't seem worth the trouble to come up with a better solution in the short-term that was just going to get replaced anyway.

**Comment by DigitalProf** [comment]
Understood! While we could perhaps develop a better UI, I suggest that we can do something simple right away. My reasoning is that these options might make sense to us (to some of us at least... to Logan alone? :-)  ), but they will not make sense to most (all?) of the typical teachers using Ayamel. Would it not make sense to pick two or three common aspect ratios that will work or most videos and provide those as options?

**Comment by schyatt** [comment]
I have to agree with Dr. Bush. I know the options have little meaning to me...
