### ISSUE TITLE
Firefox gets an "unresponsive script" warning when there are too many subtitle choices

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#640]
For Firefox on [this particular video](https://ayamel.byu.edu/content/2447), when I click on "CC" to bring up all the subtitle tracks the browser pauses for a few moments and then brings up this error:
![screen shot 2015-08-28 at 2 18 10 pm](https://cloud.githubusercontent.com/assets/5481718/9556164/f2ac5592-4d8f-11e5-8229-cde5d95d1d31.png)

This error keeps popping up until all of Firefox becomes unresponsive.

**Comment by gliese1337** [comment]
Looks like it gets stuck in the resizing loop where it tries to calculate how many columns are needed. Firefox seems not to update the layout of the element until the JavaScript terminates, so the loop continues forever trying to add more columns because it doesn't see the layout changing. Making the loop asynchronous ought to fix this, though it will slow down menu display by a few milliseconds in Chrome.

**Comment by gliese1337** [comment]
On further investigation, it looks like that wasn't it. Rather, Firefox just isn't respecting multi-column layouts, despite the MDN documentation that says it should. So, we'll need to find some other way of handling the caption menu overflow.

**Comment by gliese1337** [comment]
Turns out the Firefox uses a different capitalization convention for accessing prefixed CSS properties in JavaScript than Chrome does. Fixed the capitalization, and now it sets the column count correctly and there's no infinite loop.
