### ISSUE TITLE
CaptionAider is Executing xAPI Calls

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#651]
CaptionAider seems to be trying to make calls to xAPI:

![image](https://cloud.githubusercontent.com/assets/7268293/9661731/5327b3f2-5219-11e5-8f72-23539440cb93.png)

**Comment by schyatt** [comment]
This is not an issue on the beta site.

**Comment by gliese1337** [comment]
@DigitalProf It looks like CaptionAider has always made ActivityStream calls, just as if you were viewing the video normally. It makes sense that it would therefore also make xAPI calls now that that recording option has been added.

It's failing to actually do so because the xAPI library from ADL isn't included on editor pages. Adding that file to the CaptionAider page would be trivially easy, and then the errors would go away.
Removing both logging systems from CaptionAider would require some more significant  re-architecting, but is doable. Do we want to do that?

**Comment by gliese1337** [comment]
Final decision: do not do any logging from editor pages.
