### ISSUE TITLE
Fix the embed code system

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#665]
Right now a user can click on "Share" and then access an "embed code." That embed code can then be displayed on a webpage.

But while the title in the iFrame displays properly, it will not display content right now.

<img width="1097" alt="screenshot 2015-09-28 12 52 00" src="https://cloud.githubusercontent.com/assets/5481718/10145358/d3841c32-65df-11e5-8083-160a7c5490b6.png">

The video and subtitles and the three tabs (Transcript, Definitions, Annotations) should display in the embedded player.

Here's a [sample embed code](https://ayamel.byu.edu/content/2451) to test with:
```<iframe src="https://ayamel.byu.edu/content/2451/access/88226f3d5bb57c67e6bc8a8ad4ce6d1a?embed=true" style="border: none; height: 375px; width: 840px;"></iframe>```

**Comment by DigitalProf** [comment]
I tested this by creating a simple Web page at arclite.byu.edu/temp2/index.html with these results:

![image](https://cloud.githubusercontent.com/assets/7268293/10147604/2823faee-65ec-11e5-94dd-1fc3387fdf66.png)

**Comment by DigitalProf** [comment]
Reopened because this is not yet working correctly:

Here is an embed code provided by Ayamel:
<iframe src="https://ayamel.byu.edu/content/4165/access/f0cc3031bb7850db5e8a44e852af5bda?embed=true" style="border: none; height: 515px; width: 840px;"></iframe>

It was implemented as shown below, which yielded the results as shown in the graphic that follows Note that the gray bar opens up a banner that has the title of the video on the left and the Ayamel logon the right. It is [demonstrated at this URL](http://michaeldbush.net/test/)
![image](https://cloud.githubusercontent.com/assets/7268293/17557224/974d01d2-5ed3-11e6-9327-21e245a168d9.png)
).
<html>
<body>
<H1>The Ayamel player appears here!</H1>
<iframe src="https://ayamel.byu.edu/content/4165/access/f0cc3031bb7850db5e8a44e852af5bda?embed=true" style="border: none; height: 515px; width: 840px;"></iframe>
</html>
</body>
![image](https://cloud.githubusercontent.com/assets/7268293/17557065/f24c94ae-5ed2-11e6-8b6e-da6f8c532105.png)

**Comment by DigitalProf** [comment]
I tested again after clearing the cache on my browser. The YouTube video is now sized correctly, but the the title bar with logo still overlays the video a bit and tabs a bit, appearing with mouse-over action:

![image](https://cloud.githubusercontent.com/assets/7268293/17563746/fd862ae0-5eed-11e6-9596-1b63748a673c.png)
