### ISSUE TITLE
Apostrophe Causes Annotation to Fail

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#681]
This content object: https://ayamel.byu.edu/annotations/2772/

Contains a string ("Rydberg's equation") that shows up in the editor and then causes the last two of these errors to occur:

![image](https://cloud.githubusercontent.com/assets/7268293/10494020/4e4febc4-7271-11e5-805c-72a2a79bafcd.png)

![image](https://cloud.githubusercontent.com/assets/7268293/10494890/28d782c6-7276-11e5-9869-09e965f7245f.png)

Also, the annotation is neither editable in the editor nor visible in the player:

![image](https://cloud.githubusercontent.com/assets/7268293/10494381/53d3b830-7273-11e5-8fd9-2c51296ecfc2.png)

**Comment by gliese1337** [comment]
The problem is that that's not actually a regular apostrophe. It's something weird. Cf. "Rydberg’s" (copied-and-pasted out of the subtitle) vs. "Rydberg's" (with a regular typed apostrophe).

The annotator should be able to handle the funky characters, if we can figure out how, but at the moment I am not certain how to make it do so. The workaround is to just use a regular normal apostrophe.

**Comment by verdude** [comment]
There are two consecutive spaces in "Rydberg’s  Equation". The browser converts one of them into &nbsp;. The annotator tries to find "Rydberg’s&nbsp; Equation" in the cue and does not.

I fixed this in the annotation editor by selecting the textContent rather than the innerHTML.

I'm not sure if I should change anything in the annotator to compensate for the HTML in this particular case. The workaround would be to remove double spaces in captions.

**Comment by verdude** [comment]
There are two consecutive spaces in "Rydberg’s Equation". The browser converts the first one into ``` &nbsp;```. The annotator tries to find "Rydberg’s  Equation" in the cue and does not.

I fixed this in the annotation editor by selecting the textContent rather than the innerHTML.

I'm not sure if I should change anything in the annotator to compensate for the HTML in this particular case. The workaround would be to remove double spaces in captions.
