### ISSUE TITLE
CaptionAider Changes aren't saving

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#682]
I was trying to edit the captions of this video:  https://ayamel.byu.edu/content/1674 and got this error when I tried to save to the server:
![1](https://cloud.githubusercontent.com/assets/10120523/10499951/9368b946-7291-11e5-8bb9-7c801e65a895.PNG)

**Comment by schyatt** [comment]
I'm not getting this error again, so maybe nothing is broken.

**Comment by gliese1337** [comment]
This can happen for a hundred different reasons that have nothing to do with CaptionAider, and we expect it to sometimes- which is why we have a dialog box for it, instead of failing silently or crashing the browser window.
If it only happened once, you probably just had a bad wifi connection at the time, or something like that.
