### ISSUE TITLE
sidebar disappears when window is certain size

### ISSUE THREAD

**Issue by verdude** [BYU-ARCLITE/Ayamel-Examples#694]
The sidebar disappears occasionally at different sizes. The rest of the player is functional while the sidebar is gone. Issue on both ayamel and ayamelBeta.

[![https://gyazo.com/830349107f40fba2128df912a99e6257](https://i.gyazo.com/830349107f40fba2128df912a99e6257.gif)](https://gyazo.com/830349107f40fba2128df912a99e6257)

Sorry about the bad gif.

**Comment by gliese1337** [comment]
Might be related to #709

**Comment by gliese1337** [comment]
Nope, not related to #709! It was a problem with calculating the proper widths for the main windows vs. sidebar that caused the sidebar to end up getting pushed below the main window (and thus outside of the overflow clipping area). Setting the sidebar position to "absolute" instead of "relative" seems to fix it.
