### ISSUE TITLE
Can't see inactive subtitles in content configuration if not an administrator

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#695]
Right now a normal user cannot see the captions they upload.
They will not show up under "Edit Configuration" or "Text->Captions/Subtitles."

However, if a user is an administrator, they can see everything that has been uploaded:
https://ayamel.byu.edu/content/2825

Proxy as user: daganholbrook@gmail.com in order to see that he cannot see his own uploaded subtitles.

**Comment by JKJensen** [comment]
This also occurs when cloning a video with subtitles. The normal user will be unable to see or view the captions at all. The only one who can see the hidden captions to enable them is an administrator.

**Comment by gliese1337** [comment]
Turns out we weren't bothering to save resource owner IDs, so the system didn't know that the things you uploaded actually belong to you.
That should be fixed now, but unfortunately there's no way to go back and automatically restore the information for anything that already exists.

Also, it only explains the "Captions/Subtitles" list, not the problem with the configuration dialog. That seems to be an as-yet unknown problem with how we figure out who can edit which content items.
