### ISSUE TITLE
Annotation Editor Fails to Reset "Dirty" Bit

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#700]
After saving the annotations for a video, the user wants to leave the editor. The editor puts up the "Confirm Navigation" popup as if the annotations had not been saved, when in fact they were saved.
![image](https://cloud.githubusercontent.com/assets/7268293/11076115/3db710b2-87b6-11e5-99f5-738a034a9b02.png)

**Comment by verdude** [comment]
This is working properly on the beta site.
 
We just need to do another release to get the code on the main site.

I caught some errors that Logan was talking about concerning case sensitivity with the server switch. But, I'm not sure that everything has been found yet.

I think we would need to do some testing on the beta site (if that hasn't already been done) to find any other potential dependency errors and then we would push the changes to the main site.

If we feel confident that our testing since the server switch has found all of the issues, then we might be able to update the main site right away.
