### ISSUE TITLE
xAPI Calls in CaptionAider

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#722]
Some xAPI calls are apparently still being made in CaptionAider

![image](https://cloud.githubusercontent.com/assets/7268293/12274818/e58d7b74-b929-11e5-9393-cf43be2856e0.png)

**Comment by gliese1337** [comment]
It looks more like "CaptionAider is trying to make xAPI calls, but failing because one of the necessary libraries is not loaded."
The calls to xAPI are part of the generic Content Renderer; pulling them out would be possible, but annoying.
The simplest good solution is probably to just add a switch to the xAPI library to turn recording "on" and "off" on different pages.
