### ISSUE TITLE
Captionaider will not launch for audio files

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#727]
When I launch into Captionaider on this [audio content](https://ayamel.byu.edu/content/3274), [none of the Captionaider controls](https://ayamel.byu.edu/captionaider/3274/0) or video player become visible.

**Comment by gliese1337** [comment]
Well, this is interesting. Apparently, somebody (for all I know it was me, I haven't checked the commit history to see) introduced code into CaptionAider to refuse to play anything other than video content, and then *not* bother to tell the user or handle the error in any way.
I'm not sure what the best way to handle this is, since I don't know why that code was added in the first place, so I don't know if we need to just remove it, or finish whatever it was supposed to do so it works sensibly. But this should get fixed reasonably soon.

**Comment by gliese1337** [comment]
For now, I've just removed the code that explicitly break non-video content. If this reveals additional problems with captioning non-videos, we'll deal with them as they arise.

**Comment by JKJensen** [comment]
I still can't access captionaider for audio files on either the [beta](https://ayamelbeta.byu.edu/captionaider/666/0)or [main site](https://ayamel.byu.edu/captionaider/3274/0).
