### ISSUE TITLE
Using `ractive.data` is no longer supported

### ISSUE THREAD

**Issue by dro248** [BYU-ARCLITE/Ayamel-Examples#734]
![ractiveissue](https://cloud.githubusercontent.com/assets/11342204/12895303/0ed54f40-ce59-11e5-9205-dcecd154c3db.PNG)

**Comment by dro248** [comment]
Does this error mean that we need to update our version of the Ractive library?

**Comment by gliese1337** [comment]
No. It means we need to update our code that uses Ractive, because I already updated our version of Ractive so that the batch uploader would work. I have already done a bunch of that updating, and I was pretty sure I caught all of the instances of Ractive.data in our codebase. Where did this one come from?
