### ISSUE TITLE
Y-Lex: "Clone with Translation" English to Japanese gets caught on WWWJDIC dictionary instead of going to Google translate

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#735]
On [this video in captionaider](https://ayamelbeta.byu.edu/captionaider/627/0), when I take the Japanese subtitles and translate them to English, instead of going through Google translate, they go through the WWWJDIC dictionary.

Only the first word in the Japanese Cue is taken, and then the WWWJDIC dictionary entry for that first Japanese word is used.

For example:
Input Cue:
まずコントロールを紹介します。

Output: (Definition for the word: まず)
先ず [まず] /(adv) (1) (uk) first (of all)/to start with/about/almost/anyway/well/now

Preferred output: (From Google translate)
First, we will introduce the controls .

**Comment by gliese1337** [comment]
Sounds like a problem with the WWWJDIC interface.

**Comment by gliese1337** [comment]
After looking at the WWWJDIC interface, I don't see a straightforward way to deal with it, apart from actually getting around to implementing Japanese wordbreaking ourselves.
The best solution might be to simply finally start adding "requested data" fields to the Y-Lex request API, so that we can specifically request "translation text", and then check which services can actually provide that.

**Comment by gliese1337** [comment]
I have begun working on implementing the proper structured response format for Y-Lex that we were planning last August, because this is exactly the crisis situation that provides motive and justification for doing so.
I expect that'll take a couple of days, plus needing to update the Ayamel software to match the altered API, and then fixing this issue should be trivial.

**Comment by gliese1337** [comment]
I've got all of the service interfaces except Madamira and Collins (which weren't working properly yet anyway) updated to return structured responses. It'll need testing, but presuming my updates actually work, the next step is implementing field requests in the Y-Lex API so we can make sure to get translations back when we want them.

**Comment by gliese1337** [comment]
This should now be tracked under https://github.com/BYU-ARCLITE/DictionaryLookup/issues/15
