### ISSUE TITLE
CaptionAider- TTML subtitle tracks will not display text box to write captions when hovered over a cue.

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#746]
The TTML subtitle track format will not allow cues to have text inputted inside of it.
![ttmlsubtitleproblem](https://cloud.githubusercontent.com/assets/5481718/13194358/5a8e8f90-d74c-11e5-9ab1-cc45f6b9f87d.gif)

For .SRT and other subtitle formats, the input box displays to enter in cue text, but for TTML it does not.

[Sample video](https://ayamelbeta.byu.edu/captionaider/671/0).

**Comment by gliese1337** [comment]
It appears that what's actually happening is that the caption box is being displayed- it's just 1 pixel high, so very hard to see, and not editable, because the functions to transform HTML-styled text in an editor box into TTML text don't exist.

So, someone needs to write the editor interface for the TTML codec.

It looks like TTML cues with pre-existing text in them are displayed just fine (although we may need to double-check on the font size calculations).
