### ISSUE TITLE
Ayamel mainsite annotations bar on chrome still broken

### ISSUE THREAD

**Issue by natatat9** [BYU-ARCLITE/Ayamel-Examples#754]
#748
Link to replicate:  https://ayamel.byu.edu/content/131

![image](https://cloud.githubusercontent.com/assets/16259543/13505318/ec99fd50-e135-11e5-9202-12288783a99b.png)

So, I went back to check to see if the player had been fixed since the last time I reported it.  Firefox is looking great, but Chrome still can't handle having all four tabs open with out displaying it weird.  My wordlist seems to wrap around starting at the bottom and ending at the top.

**Comment by gliese1337** [comment]
If you know it's a duplicate of #748, please re-open the old issue instead of creating a brand new one. Also, check to see if it's broken on the beta site- if it *isn't*, that means the issue has been fixed, and we just haven't gone through a new release cycle yet. In that case, the issue should be re-opened *only* if it is high-enough priority to require a hotfix (i.e., making alterations to the live site outside of the normal development pipeline).

**Comment by natatat9** [comment]
Sorry about that!  Sounds good, I will do that from now on.
