### ISSUE TITLE
Subtitle tracks are cloned, not overwritten

### ISSUE THREAD

**Issue by dro248** [BYU-ARCLITE/Ayamel-Examples#756]
![captionaider_issue](https://cloud.githubusercontent.com/assets/11342204/13753808/2c8c945c-e9da-11e5-8256-ee75c05b7193.png)

As shown in the image above, subtitle tracks that are resaved are cloned rather than overwritten.

**Comment by JKJensen** [comment]
This issue is a problem on both the [Beta site](https://ayamelbeta.byu.edu/content/690) and the [main site](https://ayamel.byu.edu/content/3910).

When a user goes into Captionaider and saves a new subtitle track, it creates a single saved track. However, if they edit and then save that same track again, Captionaider will create a duplicate track with the new subtitles.

Editing a track should destroy the previous copy and replace it with the currently saved version.

This issue was fixed a while ago. You may want to view the commits and see what might have broken this again.

**Comment by gliese1337** [comment]
I have been unable to replicate this on either the main or beta site.
