### ISSUE TITLE
Add Native Languages to the language selection box

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#774]
Right now when a user selects a language from the drop down selection box, each language is in English.

<img width="349" alt="screenshot 2016-05-02 16 00 00" src="https://cloud.githubusercontent.com/assets/5481718/14969800/88ed2572-1081-11e6-9018-6c74153702e1.png">

The language select box should look more like this:
![ayamelnativelanguagesupport](https://cloud.githubusercontent.com/assets/5481718/14969848/d5531b74-1081-11e6-849a-2d8a1720a766.png)

The list of Ayamel supported languages and their corresponding native versions [are available here](https://docs.google.com/spreadsheets/d/1eUUvQ5sOPH0f8Pbki-R2cnAexf9uIVIHODm7ewpjWuc/edit#gid=0).

Native Languages should be right aligned, while the English versions stay left aligned.

When a user types in the search box, both the English and Native Language Script should be searched. So searching the character: 日
Should bring up: [Japanese       日本語]

Languages that are the same as both Native and English have been marked as "Same" on the spreadsheet. Do not put any extra information.

**Comment by gliese1337** [comment]
I have updated the superselect to include this functionality, so all that's left is updating the LangCode database to include native names. I have done that for the first few in order to prove that it works, but copying and pasting all of these is incredibly tedious, so I'm assigning @JKJensen to do it so that I can work on actual coding for other bugs & features.

So, here's what you need to do:
1. Check out the develop branch of the Ayamel.js repository.
2. Edit LangCodes.js (https://github.com/BYU-ARCLITE/Ayamel.js/blob/develop/js/LangCodes.js), adding the localized name for each language in that spreadsheet, keyed by its own language code, in addition to the "eng" name of the language.
3. Commit & push those changes to the develop branch on GitHub.
4. Close this issue.

Within 24 hours after all that, the localized names should appear on the beta site.

**Comment by gliese1337** [comment]
Well, nevermind. I got bored and finished all of the languages from the spreadsheet on my own after all.
