### ISSUE TITLE
Captions/Subtitles pane: Detect if the name of the subtitle file being uploaded contains the name of a language

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#785]
When a user uploads a subtitle file in Captions/Subtitle pane, they usually have the name of the Language in the name of the subtitle file.

<img width="1110" alt="screenshot 2016-05-19 17 45 33" src="https://cloud.githubusercontent.com/assets/5481718/15413635/9843dcac-1def-11e6-85b8-3d7762f5aa4a.png">

This upload utility should parse the title of the subtitle file and detect if there is a name of a language in the file that matches a language name on Ayamel.

If it matches the name, then the language select box should select that language.

**Comment by gliese1337** [comment]
This is... really complicated. A basic implementation would be fairly trivial, but also incredibly slow, probably causing the user to think their browser had become non-responsive every time they select a file for upload (because it *would* become non-responsive!).

There are ways to make it fast, but they are not simple, and it's not obvious what the right approach is. This may take some extensive experimentation. And it would probably be worth building as an independent library, which could be re-used in other projects.

**Comment by gliese1337** [comment]
After a little research, it looks like the Aho-Corasick string set matching algorithm is just what we need for this. There are plenty of opportunities for optimization with caching and such, but I might be able to get a usable version done today.

**Comment by gliese1337** [comment]
OK, I actually mostly figured this out. My JS implementation of Aho-Corasick is in fact fast enough to use for this application. Unfortunately, there are problems when you try to programmatically set the value of the language SuperSelect. So, I've put my work so far on a new ahocorasick branch. If we can figure out how to fix the UI problems that crop up when programmatically assigning a language code, then we can merge it back into the main develop branch.
