### ISSUE TITLE
Cannot click forward more than once while the video is paused

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#788]
Right now, if a user _pauses_ the Ayamel Player and clicks on the "Forward" button to go to the next caption, it will move forward once. But then after that, clicking the forward button will not continue moving forward.

![bugclickingforward](https://cloud.githubusercontent.com/assets/5481718/15553832/3e8619d0-227e-11e6-9f92-f314de596259.gif)

_Playing_ the video while pressing the forward/backward buttons works fine.

The forward button should move the cue the user is looking at up by one every time, including while paused.

[Sample video to play with.](https://ayamelbeta.byu.edu/content/693)

**Comment by gliese1337** [comment]
@JKJensen Do we know if this an issue on anything other than YouTube videos?

**Comment by gliese1337** [comment]
OK, I've figured out the cause: clicking the forward button doesn't take you quite far enough to actually activate the cue it's supposed to be taking you to, due to I-frame issues. The question of whether this happens on videos from other sources still stands, though; we need to know whether to look at this as youtube plugin issue, or a generic player issue. Either way, it may or may not actually be fixable in an acceptable manner....
