### ISSUE TITLE
Add Cantonese/Mandarin/Hawaiian to the list of language options

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#800]
On the list of languages selection screen, add Cantonese Chinese and Mandarin Chinese to the options list.
<img width="449" alt="screenshot 2016-06-06 15 43 51" src="https://cloud.githubusercontent.com/assets/5481718/15838859/7f9cab4a-2bfd-11e6-8d82-da7b647ac114.png">

**Comment by JKJensen** [comment]
Add Hawaiian to the list of languages too!

**Comment by gliese1337** [comment]
This is going to depend on the as-yet-undone efficiency improvements to the superselect control. Connected with #774

**Comment by gliese1337** [comment]
OK, so the easiest way to add all of these specifically-requested languages is just to activate the complete 7000+ list of all languages recognized by the ISO-639-3 registry. We did that once, but it ends up making things way too slow to be usable. As a result, we need to re-write the SuperSelect control to not use Ractive, because that's where all the overhead is. That's complicated, though, because, if it's not implemented as a Ractive Partial Template, then we can't insert it into other Ractive templates, which means re-writing a whole bunch of other stuff that uses Ractive....

Except today I found the docs on how to write a Ractive "decorator", and it looks like that is exactly what we need: http://docs.ractivejs.org/latest/writing-decorator-plugins

That should allow us to write a SuperSelect control that can be used on its own *or* inserted into a Ractive template, without actually relying on any of Ractive's own internals.

**Comment by JKJensen** [comment]
Woah, 7000 languages? That seems a bit excessive.

Is there any way we could add languages on a case by case basis? Or would it be easiest just to add all these at once?

**Comment by gliese1337** [comment]
It's possible- we did it with Egyptian & Levantine Arabic- but it gets progressively more unwieldy and difficult to maintain the more special cases we have. It is much, much easier to just say "use everything from this standard list". So far, we've been using the ISO 639-1 list. So, if we need to add a whole bunch of new languages that aren't on that list, the simplest way to do it is to just start using the complete ISO 639-3 list instead.
